# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  knoex:
    image: knoex
    build:
      context: .
      dockerfile: Knoex/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5142:5142
      - 7017:7017
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
